### PR TITLE
Chart changes [ DB ] [ part 1 of 4 ]

### PR DESCRIPTION
**Pull request by jbygdell**
This is part 1 in a series of PRs that will change how the charts are deployed.
Since all PRs are connected they need to be merged in series, hence the next will be craeted once this one is merged.

*This is a breaking change, older versions of the values file will not work any more.*

## Changes made
1) Chart version bumped to v0.4.0
2) Moved the default container repo from Docker Hub to GitHub Container Repository
3) The chart can now be deployed with TLS disabled by setting `global.tls.enabled=false`
4) Secret for the servers TLS certificates will have to be created manually from now on. This is in order to facilitate a smoother deployment, i.e. `helm install postgres neicnordic/sda-db -f values.yaml`

### CODE REVIEW

**Review by blankdots — APPROVED** [review]
the code looks sound.

My understanding is that this part 1 introduces `notls` and we use that in the integration tests. I assume in the next parts we will bring back and test also with TLS ?

**Comment by jbygdell** [comment]
> the code looks sound.
> 
> My understanding is that this part 1 introduces `notls` and we use that in the integration tests. I assume in the next parts we will bring back and test also with TLS ?

Tests are still done with TLS as `noTLS=false`, the tests without TLS is something we should create in the future.

**Review by norling — APPROVED** [review]
There was a weird comment, but looks good otherwise.

**Review by dbampalikis — APPROVED** [review]
Created an issue regarding the `release-test-deploy.yaml`. Otherwise it looks good

**Review by kostas-kou — APPROVED** [review]
Looks good

**Pull request merged**
